# UI Configuration
ui.base.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
ui.browser=chrome
ui.implicit.wait=10
ui.explicit.wait=20
ui.headless=false

# API Configuration
api.base.url=https://api.restful-api.dev
api.request.timeout=5000

# Logging
log.level=INFO

