name: Maven Build and Test

# This tells GitHub when to run the project
on:
  push:
    branches: [ "main", "master" ]  # Runs every time you push code
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-cucumber-project .

      - name: Run Tests in Docker
        run: docker run my-cucumber-project